-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-11-04 12:22:59.016

-- tables
-- Table: APODERADO
CREATE TABLE APODERADO (
    CODAPO char(6)  NOT NULL,
    TIPDOCIDEAPO varchar(30)  NOT NULL,
    NOMAPO varchar(50)  NOT NULL,
    APEAPO varchar(50)  NOT NULL,
    CELAPO char(9)  NOT NULL,
    EMAAPO varchar(40)  NOT NULL,
    DOMAPO varchar(100)  NOT NULL,
    GENAPO varchar(10)  NOT NULL,
    TRAAPO varchar(50)  NOT NULL,
    PROAPO varchar(50)  NOT NULL,
    IDIOAPO varchar(50)  NOT NULL,
    CONVIESTAPO varchar(20)  NOT NULL,
    TAMFAMAPO int  NOT NULL,
    NACAPO varchar(40)  NOT NULL,
    ESTCIVAPO varchar(60)  NOT NULL,
    CONSTRAINT APODERADO_pk PRIMARY KEY (CODAPO)
);

-- Table: ESTUDIANTE
CREATE TABLE ESTUDIANTE (
    CODEST char(8)  NOT NULL,
    TIPDOCIDENEST char(8)  NOT NULL,
    NOMEST varchar(50)  NOT NULL,
    APEEST varchar(50)  NOT NULL,
    CELEST char(9)  NOT NULL,
    FECNAEST date  NOT NULL,
    DOMEST varchar(100)  NOT NULL,
    LUGNACEST varchar(80)  NOT NULL,
    DEPEST varchar(50)  NOT NULL,
    EMAEST varchar(50)  NOT NULL,
    TIPDOCIDEST varchar(20)  NOT NULL,
    DISEST varchar(30)  NOT NULL,
    NACEST varchar(40)  NOT NULL,
    IDIEST varchar(40)  NOT NULL,
    GRAEST varchar(30)  NOT NULL,
    ESTEDUEST varchar(60)  NOT NULL,
    CONSTRAINT ESTUDIANTE_pk PRIMARY KEY (CODEST)
);

-- Table: MATRICULA
CREATE TABLE MATRICULA (
    CODMAT char(9)  NOT NULL,
    FECHORMAT date  NOT NULL,
    NUMVACMAT int  NOT NULL,
    TIPMAT varchar(80)  NOT NULL,
    CODAPO char(6)  NOT NULL,
    CODEST char(8)  NOT NULL,
    CONSTRAINT MATRICULA_pk PRIMARY KEY (CODMAT)
);

-- Table: REGISTRO_I_E_P
CREATE TABLE REGISTRO_I_E_P (
    IDREGIEP int  NOT NULL,
    NOMCOLREGIEP varchar(80)  NOT NULL,
    CODMAT char(9)  NOT NULL,
    CODSECCON char(9)  NOT NULL,
    CONSTRAINT REGISTRO_I_E_P_pk PRIMARY KEY (IDREGIEP)
);

-- Table: SECRETARIA_CONSULTAS
CREATE TABLE SECRETARIA_CONSULTAS (
    CODSECCON char(9)  NOT NULL,
    DNI char(8)  NOT NULL,
    NOMSECCON varchar(60)  NOT NULL,
    APESECCON varchar(60)  NOT NULL,
    CELSECCON char(9)  NOT NULL,
    EMASECCON varchar(80)  NOT NULL,
    CODAPO char(6)  NOT NULL,
    CONSTRAINT SECRETARIA_CONSULTAS_pk PRIMARY KEY (CODSECCON)
);

-- foreign keys
-- Reference: APODERADO_MATRICULA (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT APODERADO_MATRICULA
    FOREIGN KEY (CODAPO)
    REFERENCES APODERADO (CODAPO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: APODERADO_SECRETARIA_CONSULTAS (table: SECRETARIA_CONSULTAS)
ALTER TABLE SECRETARIA_CONSULTAS ADD CONSTRAINT APODERADO_SECRETARIA_CONSULTAS
    FOREIGN KEY (CODAPO)
    REFERENCES APODERADO (CODAPO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_ESTUDIANTE (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_ESTUDIANTE
    FOREIGN KEY (CODEST)
    REFERENCES ESTUDIANTE (CODEST)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_REGISTRO_I_E_P (table: REGISTRO_I_E_P)
ALTER TABLE REGISTRO_I_E_P ADD CONSTRAINT MATRICULA_REGISTRO_I_E_P
    FOREIGN KEY (CODMAT)
    REFERENCES MATRICULA (CODMAT)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: SECRETARIA_CONSULTAS_REGISTRO_I_E_P (table: REGISTRO_I_E_P)
ALTER TABLE REGISTRO_I_E_P ADD CONSTRAINT SECRETARIA_CONSULTAS_REGISTRO_I_E_P
    FOREIGN KEY (CODSECCON)
    REFERENCES SECRETARIA_CONSULTAS (CODSECCON)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

